## Chapter 2-Tensors

Simple CPU Example

In [1]:
import torch

x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[7,8,9],[10,11,12]])
z = x + y
print(z)
print(z.size())

tensor([[ 8, 10, 12],
        [14, 16, 18]])
torch.Size([2, 3])


Simple GPU Example

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
x = torch.tensor([[1,2,3],[4,5,6]], device = device)
y = torch.tensor([[7,8,9],[10,11,12]], device = device)
z = x + y
print(z)

print(z.size())
print(z.device)

tensor([[ 8, 10, 12],
        [14, 16, 18]], device='cuda:0')
torch.Size([2, 3])
cuda:0


Moving Tensors between CPU & GPU

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
x.to(device)
y.to(device)
z = x + y
z.to("cpu")

tensor([[ 8, 10, 12],
        [14, 16, 18]])

Creating Tensors

In [4]:
import numpy
# Created from pre-existing arrays
w = torch.tensor([1,2,3])
w = torch.tensor((1,2,3))
w = torch.tensor(numpy.array(numpy.array([1,2,3])))

# Initialized by size
w = torch.empty(100,1200)
w = torch.zeros(100,200)
w= torch.ones(100,200)

1. from a list
2. from a tuple
3. from a numpy array
4. uninitialized, elements values
are not predictable
6. all elements initialized with 0.0
7. all elements initialized with 1.0

In [5]:
w = torch.rand(100,200) # 1
w = torch.randn(100,200) # 2
w = torch.randint(5,10,(100,200)) # 3

w = torch.empty((100,200), dtype=torch.float64,
                device="cuda")

x = torch.empty_like(w)

1. Creates a 100 x 200 tensor with elements from a uniform distribution on the interval [0, 1)
2. elements are random numbers from a normal distribution with mean 0 and variance 1
3. elements are random integers between 5 and 10

Data Types

In [6]:
# Specify data type at creation using dtype
w = torch.tensor([1,2,3], dtype = torch.float32)

# Use casting method to cast to a new data type
w.int()     # w remains a float32 after cast
w = w.int()     # w changes to int32 after cast

# Use to() method to cast to a new type
w = w.to(torch.float64)
w = w.to(dtype = torch.float64)

# Python automatically converts data types during operations
x = torch.tensor([1,2,3], dtype = torch.int32)
y = torch.tensor([1,2,3], dtype = torch.float32)
z = x + y
print(z.dtype)

torch.float32


Tensor Operations

In [9]:
x = torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(x)

# Indexing, returns a tensor
print(x[1,1])
# Indexing, returns value as Python number
print(x[1,1,].item())

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor(4)
4


In [10]:
# Slicing
print(x[:2,1])

# Boolean indexing
# Only keep elements less than 5
print(x[x<5])

tensor([2, 4])
tensor([1, 2, 3, 4])


In [11]:
print(x.t())

print(x.view(2,4))

tensor([[1, 3, 5, 7],
        [2, 4, 6, 8]])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [12]:
# Combining tensors
y = torch.stack((x,x))
print(y)

# Splitting tensors
a,b = x.unbind(dim =1)
print(a,b)

tensor([[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]],

        [[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]])
tensor([1, 3, 5, 7]) tensor([2, 4, 6, 8])


Automatic Differentiation (Autograd)

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float, requires_grad =True)
print(x)
f = x.pow(2).sum()
print(f)
f.backward()
print(x.grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
tensor(91., grad_fn=<SumBackward0>)
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
